#!/bin/bash


Rscript SagebrushRegeneration_3_Part1a_HistoricalPatterns.R
Rscript SagebrushRegeneration_3_Part1b_FuturePatterns.R
Rscript SagebrushRegeneration_3_Part2a_Uncertainty-Agreement.R
Rscript SagebrushRegeneration_3_Part2b_Uncertainty-Sensitivity.R
Rscript SagebrushRegeneration_3_Part2d_Uncertainty-Extrapolations.R
Rscript SagebrushRegeneration_3_Part3a_EnvRelationships_Shriver2018.R
Rscript SagebrushRegeneration_3_Part3b_GeneralEnvRelationships.R
Rscript SagebrushRegeneration_3_Part3c_SoilDifferenceRelationships.R
Rscript SagebrushRegeneration_3_Part3d_GeneralFutureDiffEnvRelationships.R
